### ISSUE TITLE
Run hack/ as an individual CI test

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python-base#118]
Currently the ```hack/``` scripts are run as part of all of CI tests. An example can be seen [here](https://travis-ci.org/kubernetes-client/python-base/jobs/495736027). 

Instead, we should move the ```hack/``` scripts to an additional individual check. This saves us some build time for CI and also allows us to potentially expand the scope of ```hack/``` checks we can do in the future. As a background, see kubernetes-client/python#22

**Comment by Sai-Adarsh** [comment]
> 
> 
> Currently the `hack/` scripts are run as part of all of CI tests. An example can be seen [here](https://travis-ci.org/kubernetes-client/python-base/jobs/495736027).
> 
> Instead, we should move the `hack/` scripts to an additional individual check. This saves us some build time for CI and also allows us to potentially expand the scope of `hack/` checks we can do in the future. As a background, see [kubernetes-client/python#22](https://github.com/kubernetes-client/python/issues/22)

Hey @micw523 I'm interested with this, What do you mean by 'Additional  individual check' and some more pointers on how to fix this issue?

**Comment by micw523** [comment]
I just saw this. Have you checked one of the Travis CI’s build interface? You’ll see one if you go to any PR and click on the details next to the Travis CI build status.

You’ll see many individual tests in it. The goal is to write another test for the hack/ scripts instead of hard coding it into every test in .travis.yml.
