### ISSUE TITLE
Migrate to pytest?

### ISSUE THREAD

**Issue by oz123** [kubernetes-client/python-base#153]
Currently, the test suite uses nose while the python-client uses pytest.
I suggest migrating the tests of this project to pytest too. This will ease contributions
to both projects.

**Comment by alanjcastonguay** [comment]
It doesn't look like there's any nose-specific stuff going on here, it's all standard module `unittest` and nose is only being used as the test runner. pytest would be nearly a drop-in replacement, other than the coverage configuration. Does that match your understanding? Did you want to make a PR?

**Comment by oz123** [comment]
@alanjcastonguay yes, I would like to make a PR for that.

**Comment by scottilee** [comment]
@oz123 any update on this? Do you want to assign the issue to yourself?
