### ISSUE TITLE
Open ssl certificate verify failed

### ISSUE THREAD

**Issue by svivier-orange** [kubernetes-client/python-base#177]
Cant use the InClusterConfigLoader with an self signed ca.cert   
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate ferify failed: self signed certificate in certificate chain`
I propose to add a parameter or an env variable to allow a verify=false .

**Comment by alanjcastonguay** [comment]
You should be able to pass an arbitrary ca-certificate file (eg the public half of your self-signed cert) to `InClusterConfigLoader()` today. Is that not feasible? https://github.com/alanjcastonguay/python-base/blob/master/config/incluster_config.py

**Comment by svivier-orange** [comment]
I've found a (temporary) workaround, the Configuration object is global scoped and use default values, whom can be writted before the InClusterConfigLoader (as long as InClusterConfigLoader don't override it, wish is the case for verify_ssl).

**Comment by roycaihw** [comment]
InClusterConfigLoader [overrides the default object](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/config/incluster_config.py#L84). You could set `verify_ssl` to False in a local Configuration object after `load_incluster_config` and use it with you clients.

**Comment by svivier-orange** [comment]
Thanks for your help
