### ISSUE TITLE
Watch break when request func faild on "ConnectionError", should  retry automatically

### ISSUE THREAD

**Issue by DrAuYueng** [kubernetes-client/python-base#189]
In watch.py, the stream while loop will break on  ConnectionError, should  retry automatically.
like this:

    def do_func(self, func, *args, **kwargs):
        resp = None
        try:
            resp = func(*args, **kwargs)
        except IOError:
            if 'retry_after' in kwargs:
                retry_after = kwargs['retry_after']
            else:
                retry_after = 1
            time.sleep(retry_after)
        return resp

**Comment by NikPaushkin** [comment]
@DrAuYueng I've tried to disable my laptop network adapter and I even didn't get any exception from watcher: it just stuck. So, I think, more research needed for disconnect cases.
