### ISSUE TITLE
ws_client.py could not handle binary as stdout

### ISSUE THREAD

**Issue by walthhy** [kubernetes-client/python-base#192]
k8s python client: 11.0.0
python 3

We're using following block copying files/dirs from pod to local, however, ws_client would decode(utf-8) data frame from socket into str, which would break the function. Enhancement needed for function ```def update(self, timeout=0)``` to store data based on type into channels. 

```python
    exec_command = ['tar', 'cf', '-', '/var']

    with TemporaryFile() as tar_buffer:
        resp = stream(api_instance.connect_get_namespaced_pod_exec, pod_name, namespace,
                      command=exec_command,
                      stderr=True, stdin=False,
                      stdout=True, tty=False,
                      _preload_content=False)

        while resp.is_open():
            resp.update(timeout=1)
            if resp.peek_stdout():
                out=resp.read_stdout()
                tar_buffer.write(out)
            if resp.peek_stderr():
                print("STDERR: %s" % resp.read_stderr())

        resp.close()

        tar_buffer.flush()
        tar_buffer.seek(0)

        with tarfile.open(fileobj=tar_buffer, mode='r:') as tar:
            print('members', tar.getmembers())

```

**Comment by roycaihw** [comment]
We should only decode the response if [`opcode == ABNF.OPCODE_TEXT`](https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_core.py#L315-L316) (websocket-client module). Currently we are decoding binary payload as well: https://github.com/kubernetes-client/python-base/blob/bf5c59987122fd35e9bb14a939f3db94e55b30bf/stream/ws_client.py#L207-L210

We also need a e2e test case for this. I will work on this when I get a chance, or someone else may pick it up. 

/help

**Comment by iciclespider** [comment]
Here is a total curve ball observation.

I think the wrapping of the pod exec api needs to be completely reimplemented following the python subprocess.Popen constructor calling sequence as close as possible. This new implementation should return an object that then acts as close as possible to an instance of subprocess.Popen. This is a well thought out library for interacting with processes. Then python programmers that know how to interact with subprocess.Popen will be up and running doing the same with pod exec.

Then in response to this specific issue, subprocess.Popen by default handles stdin, stdout, and stderr as binary streams. The `text=True` argument specifies that these streams should be text streams.
