### ISSUE TITLE
What is the returncode if self.read_channel(ERROR_CHANNEL) doesn't return anything?

### ISSUE THREAD

**Issue by Ferenc-** [kubernetes-client/python-base#194]
First of all what I am experiencing very often is that. When I have WSClient object instantiated as such:
```python
        resp = stream(self.core_v1.connect_get_namespaced_pod_exec,
                      podname,
                      namespace_name,
                      command=exec_command,
                      stderr=True, stdin=False,
                      stdout=True, tty=False,
                      _request_timeout=kube_exec_timeout,
                      _preload_content=False,
                      )
```
When I try to get the error code after a waiting loop like this:
```python
        while resp.is_open():
            resp.update(timeout=2)
            if resp.peek_stdout():
                log("Executing...")
            if resp.peek_stderr():
                log("Error...")
```
I get:
```
 AttributeError: 'WSClient' object has no attribute 'returncode'
```
I figured I could gut out the internals and copy paste some part of the implementation in particular this:
```python
            err = self.read_channel(ERROR_CHANNEL)
            err = yaml.safe_load(err)
            if err['status'] == "Success":
                return 0
            return int(err['details']['causes'][0]['message'])
```
This is verbatim copy past from the [returncode implementation](https://github.com/kubernetes-client/python-base/blob/b87a5fe119b820e9196f39343b0f5a1546d7465b/stream/ws_client.py#L243).
And what happens here is that what we read from the `ERROR_CHANNEL` is exactly nothing,
And therefore the `yaml_safe_load` results in `None`, and then we try to index None with `'status'`,
and then Kaboom.

So my first question is why does the current implementation assume that we managed to read from the `ERROR_CHANNEL` something yaml loadable to begin with? Should there be a check?
Is it possible that the reason why I get 
```
 AttributeError: 'WSClient' object has no attribute 'returncode'
```
Is also because, perhaps some internal exception happens when the `returncode` property of `ws_client.py` tries to index a `None`?

**Comment by roycaihw** [comment]
cc @oz123

**Comment by roycaihw** [comment]
> AttributeError: 'WSClient' object has no attribute 'returncode'

This is unexpected. Could you share more code on how you invoke `returncode`? 

> why does the current implementation assume that we managed to read from the ERROR_CHANNEL something yaml loadable to begin with

Please take a look at [this snippet](https://github.com/kubernetes-client/python/blob/b6e4ae81a2afb49f668a142eb7d1c6e2571ef478/kubernetes/e2e_test/test_client.py#L142-L157) as example. The code tries to decode the apiserver response into a [Status](https://github.com/kubernetes/kubernetes/blob/6ac3ca4b1793d0eaaaa7d605e5b9b8057000e1ce/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L598-L629) kind. The return code for a exec command gets embedded in the `details` field. [Kubernetes always returns 
the `Status` kind from any API endpoint when an error occurs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#response-status-kind).

**Comment by oz123** [comment]
An exception inside `returncode` should not cause the `AttributeError`. Python is pretty specific about this, here is an example:

```
In [4]: class Foo:
   ...:     @property
   ...:     def bla(self):
   ...:         a = 1
   ...:         raise ValueError("nee...")
   ...:         return a
   ...: 

In [5]: Foo().bla
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-7d48d577f81a> in <module>()
----> 1 Foo().bla

<ipython-input-4-7bc84d191e58> in bla(self)
      3     def bla(self):
      4         a = 1
----> 5         raise ValueError("nee...")
      6         return a
```

I agree with you it's not trivial to understand that k8s always returns a status can be decoded.

>  And what happens here is that what we read from the ERROR_CHANNEL is exactly nothing,

Hmm... can you post a more complete trace of this? We need to see more information about your exceptions.

**Comment by Ferenc-** [comment]
Hi @roycaihw and @oz123,

Thank you for responding, here is for example one scenario, with a more complete trace that I just produced a few minutes ago:
```
Traceback (most recent call last):
  File "src/test.py", line 1712, in <module>
    main()
  File "src/test.py", line 1706, in main
    check_api_with_zap(zap_release)
  File "src/test.py", line 1295, in check_api_with_zap
    create_zap_wrk_dir(zap_pod_name)
  File "src/test.py", line 1179, in create_zap_wrk_dir
    kube_exec_timeout)
  File "src/test.py", line 749, in kubectl_exec
    resp.returncode
  File "/usr/lib/python3.6/site-packages/kubernetes/stream/ws_client.py", line 245, in returncode
    if err['status'] == "Success":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ferenc-** [comment]
So like I said in here in [ws_client.py](https://github.com/kubernetes-client/python-base/blob/master/stream/ws_client.py#L245):
```
            err = self.read_channel(ERROR_CHANNEL)
            err = yaml.safe_load(err)
            if err['status'] == "Success":
                return 0
            return int(err['details']['causes'][0]['message'])
```
What we get on the ERROR_CHANNEL is exactly nothing, which is not yaml loadable, and we are trying to subscript, `None['status']`.

**Comment by oz123** [comment]
Well, in this case this requires more investigation. 
Maybe something changed in Kubernetes underlying. Obviously, if the error channel is empty one should look in the STDOUT_CHANNEL.
Unfortunately, I can't provide a quick fix for this because of time constraints.

**Comment by Ferenc-** [comment]
Why would the STDOUT_CHANNEL have any useful status data?
What travels on the STDOUT_CHANNEL, is my very own application specific data from the container, and nothing from the k8s api server or kubelet. Or at least that is my empirical observation and understanding.

**Comment by bhperry** [comment]
Hitting this issue as well. `returncode` raises a KeyError because there is nothing on the ERROR_CHANNEL, even if I intentionally cause an error
