### ISSUE TITLE
ReplicationController delete propagation policy

### ISSUE THREAD

**Issue by hedrox** [kubernetes-client/python-base#242]
When running the function test_replication_controller_apis from dynamic/test_client.py, the test deletes the replication controller, but not the underlying pods. I think this happens because by default the replication controller orphans the pods when deleted, and a solution could be to set the propagation policy to background or foreground.

If you want I can submit a PR here and then also in kubernetes-client/python, because there are replication controller tests in there that suffer from the same issue.

**Comment by roycaihw** [comment]
Thanks for reporting! I didn't expect the default behavior to be orphan the pods :( It would be awesome if you could open PRs in the repos to fix those tests.

/assign @hedrox
