### ISSUE TITLE
Consider releasing python-base as an stand alone package

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python-base#25]
Python base can be re-arranged to be released as an stand alone package. Benefits are:

- Clear dependencies between main repo and base.
- A fully functional kubernetes client without convenience API calls and Models. One should be able to use it to talk json with API server's endpoints.
- Versioning, testing, etc. independent of main repo.

**Comment by pokoli** [comment]
Then you should propably remove the module stuff and add only a dependency on setup.py.

For me, this is the prefered way for python packages. So please go ahead with it!!!

**Comment by tardyp** [comment]
This will help projects like buildbot, which only needs to call a few API with asynchronous libraries, but could use the config parsers. see https://github.com/buildbot/buildbot/pull/3467

**Comment by mbohlool** [comment]
I would like to spend some time on this. Look like we need to do https://github.com/swagger-api/swagger-codegen/issues/6191 first.

**Comment by ignertic** [comment]
ANyone working on this?

**Comment by mbohlool** [comment]
@ignertic no. you are welcome to work on this if you have time.
