### ISSUE TITLE
Publish as standalone package on PyPI

### ISSUE THREAD

**Issue by mortenlj** [kubernetes-client/python-base#261]
If the intention is that alternative kubernetes clients can use python-base for "common" parts, it would be useful if the packages here was available on PyPI so you could add them as dependencies.

Either the complete package as `kubernetes-base` or similar, or even split out the individual packages `kubernetes-config`, `kubernetes-leaderelection` etc.

**Comment by roycaihw** [comment]
Today python-base is included in the python client release. Does using python-base from python package work for you? 

cc @yliaog

**Comment by mortenlj** [comment]
I assume it would work (have not made an attempt yet), but it would be overkill to include all of the client library, with all of its dependencies, when all I want is the "common" parts and maybe only a subset of those.

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
