### ISSUE TITLE
load_config is printing to stdout

### ISSUE THREAD

**Issue by hterik** [kubernetes-client/python-base#263]
In [config/__init__.py, when calling load_config ](https://github.com/kubernetes-client/python-base/blob/3aa8b4c94282707a20482f71e86624f3b39a2cc6/config/__init__.py#L39) and not running in a cluster, a warning message is printed to stdout.

This utility function might be used in context where the stdout is used for other purposes and can garble such data. 
Recommend use logging instead.

**Comment by roycaihw** [comment]
I think using logging is a good idea. Would you like to send a PR? 

/unassign
cc @yliaog @tomplus 

Some thoughts:
1. It's a behavior change. We need to make sure we document it, and existing users are okay with this change.
2. Let's make sure the behavior in [python](https://github.com/kubernetes-client/python) and [python-base](https://github.com/kubernetes-client/python-base) are consistent. I took a quick look and there aren't many places where we use `print` in this client.

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
