### ISSUE TITLE
support for asyncio

### ISSUE THREAD

**Issue by tomplus** [kubernetes-client/python-base#27]
Hi guys.

Do you consider providing this client library with support for `asyncio` ?

Regards,
Tomasz Prus

**Comment by mbohlool** [comment]
`asyncio` would be nice. I can label this PR as help-needed so somebody pick it up. It would be better if you create your proposal as an issue in the main repo that hopefully will get more attraction.

**Comment by tomplus** [comment]
@mbohlool thanks. I'll add an issue in the main repo.

**Comment by tomplus** [comment]
@mbohlool I’ve prepared the new library kubernetes_asyncio which is based on this Python client, but uses the asyncio generator from swagger-codegen. Additional PR to `gen` repository is already merged.

Do you think it's possible to migrate this new library to official kubernetes-clients' repo? How can I do that?

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
