### ISSUE TITLE
add socks5 proxy support for websocket client

### ISSUE THREAD

**Issue by lc-bitsec** [kubernetes-client/python-base#270]
connect_post_namespaced_pod_exec used kubernetes.stream.stream to execute command in pod.
I want to use socks5 type proxy in websocket connection which used by kubernetes.stream.stream.
But i didn't find any docs or apis.  So I modified the code in the file /kubernetes/stream/ws_client.py in order to use socks5 proxy websockset connection.

![image](https://user-images.githubusercontent.com/17118721/145765595-bb367f5a-b0f6-4262-a253-c046beb971ae.png)

reference: https://websocket-client.readthedocs.io/en/latest/examples.html?highlight=proxy#connecting-through-a-proxy

Hope to add support for socks proxy in the next version.

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
