### ISSUE TITLE
custom kube config cannot be loaded

### ISSUE THREAD

**Issue by pelt** [kubernetes-client/python-base#277]
The function [load_config](https://github.com/kubernetes-client/python-base/blob/master/config/__init__.py#L36) provides an option to use a custom kube config path. Unfortunately the validation of the name is wrong. It checks for [kube_config_path](https://github.com/kubernetes-client/python-base/blob/master/config/__init__.py#L36) but the invoked function uses obviously [config_file](https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L790).

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
