### ISSUE TITLE
WSClient.update() fails on select.poll() when running in eventlet on Linux

### ISSUE THREAD

**Issue by bobh66** [kubernetes-client/python-base#281]
WSClient.update() was modified by PR #268  to use select.poll() instead of select.select, which breaks when running under eventlet on Linux:

```
  File "/usr/local/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 182, in update
    poll = select.poll()
AttributeError: module 'select' has no attribute 'poll'
module 'select' has no attribute 'poll'
```

eventlet monkey_patches the select module and does not support the poll() method

Adding a check on getattr(select, "poll", None) is None to the if statement and reverting to select.select when there is no poll attribute will fix the problem.

I'll push a PR

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
