### ISSUE TITLE
Add support for bookmark events

### ISSUE THREAD

**Issue by cansjt** [kubernetes-client/python-base#286]
In #234 the parsing of BOOKMARK events has been bypassed. But those events exist for a reason and can be useful in some circumstances. And motivational example is this Airflow issue: apache/airflow#21087.

As Airflows scheduler can be stopped and restarted, while many events occur on k8s, it would need to process BOOKMARK to recover its state. Sadly because those are ignored by the Python client, it cannot. Which manifests itself in varied ways (see the different issues referenced in the ticket above)

**Comment by roycaihw** [comment]
HI @cansjt, thanks for sending the issue! This python-base repo has been merged into the main python repo, and is being archived. Would you mind sending the issue to the python repo?

**Comment by cansjt** [comment]
Done. I am guessing I can close this issue, right?

**Comment by roycaihw** [comment]
Yes. Thank you!

/close
