### ISSUE TITLE
issue with iterating over a dict

### ISSUE THREAD

**Issue by sujeeth961991** [kubernetes-client/python-base#50]
If `query_params` is a dict, the the following code fails to iterate.
https://github.com/kubernetes-client/python-base/blob/11da619c9ef7b2e26fe162e5feeb72d5bedcc5c9/stream/ws_client.py#L238

For Python 2.x:
`for key, value in d.iteritems():`
For Python 3.x:
`for key, value in d.items():`

**Comment by pokoli** [comment]
Hi @sujeeth961991,

Thanks for reporting. Could you please create a pull request to fix the issue? 

I think we should use .items() to iterate over the items, as this function will be compatible with both python versions (iteritems is removed from 3.x as the default behaviour is to return an iterator).

**Comment by iamneha** [comment]
cc @roycaihw @brendandburns

**Comment by roycaihw** [comment]
Interesting. I tried to log `kwargs` in [`websocket_call`](https://github.com/kubernetes-client/python-base/blob/8d7b6f7dc3158ff5c45fd828e965606d1c0ecfeb/stream/ws_client.py#L226) and ran [e2e tests](https://github.com/kubernetes-client/python/blob/529c0d3c2fbceca0f38d1cd3ae2eb3d5cd660a07/kubernetes/e2e_test/test_client.py#L79). It showed that `kwargs` was

```
{'body': None, 'query_params': [('command', ['/bin/sh', '-c', 'for i in $(seq 1 3); do date; done']), ('stderr', False), ('stdin', False), ('stdout', True), ('tty', False)], 'post_params': [], '_request_timeout': None, '_preload_content': True, 'headers': {'Content-Type': 'application/json', 'Accept': '*/*', 'User-Agent': 'Swagger-Codegen/8.0.0-snapshot/python'}}
```

where `kwargs.get("query_params", {})` was
```
[('command', ['/bin/sh', '-c', 'for i in $(seq 1 3); do date; done']), ('stderr', False), ('stdin', False), ('stdout', True), ('tty', False)]
```

It seems that `query_params` is not a dict but a list of tuples?

**Comment by micw523** [comment]
It is a list of tuples of a (key, value) pair:
https://github.com/kubernetes-client/python-base/blob/8d7b6f7dc3158ff5c45fd828e965606d1c0ecfeb/stream/ws_client.py#L237

**Comment by micw523** [comment]
@iamneha See code here: https://github.com/kubernetes-client/python-base/blob/8d7b6f7dc3158ff5c45fd828e965606d1c0ecfeb/stream/ws_client.py#L238-242
The (key, value) pair are appended to the query_param list - and therefore it is always a list of tuples.

**Comment by iamneha** [comment]
@micw523 I think you are confusing query_params with kwargs.get("query_params").
You can see [test_pod_apis](https://github.com/kubernetes-client/python/blob/529c0d3c2fbceca0f38d1cd3ae2eb3d5cd660a07/kubernetes/e2e_test/test_client.py#L38)
Here you will see we stream the API and send command that need to be executed. kwargs is coming from this [e2e tests](https://github.com/kubernetes-client/python/blob/529c0d3c2fbceca0f38d1cd3ae2eb3d5cd660a07/kubernetes/e2e_test/test_client.py#L79) which is in form of tuple.

And you are right, the `query_params` you are taking about is tuple. We are passing this tuple to the url which execute inidividual command params during API call

**Comment by micw523** [comment]
@iamneha You’re right. I was not talking about the correct ```query_params``` here. However, The e2e test called ```connect_get_namespaced_pod_exec```, which also packed the parameters into a list of tuples. It’s in the core_v1_api.py and it’s too large for github to show so no link here :)

**Comment by iamneha** [comment]
@micw523 yes you are right nothing needs to be changed here :)
cc @roycaihw

**Comment by roycaihw** [comment]
@iamneha @micw523 Thanks for looking into this issue :)

/close
