### ISSUE TITLE
load_kube_config fails if KUBECONFIG contains more than one file

### ISSUE THREAD

**Issue by joar** [kubernetes-client/python-base#62]
KUBECONFIG is a list of colon-deliminated config files.
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable.

load_kube_config without arguments throws:
```pytb
FileNotFoundError: [Errno 2] No such file or directory: '/home/joar/git/foo/.kube-config:/home/joar/.kube/config'
```

**Comment by matohavo** [comment]
Bump. Still an issue

**Comment by aseempatni** [comment]
I'm also facing the same issue when KUBECONFIG contains multiple files.

**Comment by tomplus** [comment]
@aseempatni which version of the library do you have? It should work with the latest one.

/remove-lifecycle stale

**Comment by aseempatni** [comment]
Ah, I see. I'm using 8.0.1. It was fixed after that I assume? Lemme give a shot with the latest one.

**Comment by tomplus** [comment]
Yes, v. 10.0.0a1 should work.
