### ISSUE TITLE
Support for client-go credential plugins authentification scheme?

### ISSUE THREAD

**Issue by Lawouach** [kubernetes-client/python-base#63]
Hey all,

Kubernetes 1.10 has introduced an alpha feature to support a greater variety of authentification mechanisms https://kubernetes.io/docs/admin/authentication/#client-go-credential-plugins

Is there planning to support this from the Python client by any chance?

Thanks,

**Comment by Lawouach** [comment]
Mm, I wonder if we should open issues here or on the top-level kubernetes client project?

cc @mbohlool if that's okay to ask :)

**Comment by roycaihw** [comment]
Closing in favor of the top-level python repo issues, which have more visibility.
