### ISSUE TITLE
Create an OWNERS file

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-client/python-base#80]
ref: https://github.com/kubernetes/community/issues/1721

This repo is listed in sigs.yaml as belonging to sig-api-machinery, but it lacks an OWNERS file.  Can you please add one with the appropriate list of approvers and reviewers? eg:
- [robust example: approvers, reviewers, aliases](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/OWNERS)
- [simple example: only approvers, no aliases](https://github.com/kubernetes-incubator/external-storage/blob/master/OWNERS)

For more information see the [OWNERS docs](https://go.k8s.io/owners)

/sig api-machinery

/assign @lavalamp @deads2k
sig-api-machinery chairs

/assign @roycaihw @yliaog @mbohlool 
as folks who've been merging PR's recently

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python-base/commit/07ef6263685802ee5a8532662bf589adaa07b592

added OWNERS file.
