### ISSUE TITLE
Watch stream duplicates events

### ISSUE THREAD

**Issue by klarose** [kubernetes-client/python-base#81]
I have been using a Watch stream to handle events for my custom resource. I have found that the same events are repeated indefinitely even though nothing has changed on the system.

Here is an example. I have a custom resource defined as follows:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hobbitses.test.example
spec:
  group: test.example
  version: v1
  scope: Namespaced
  names:
    plural: hobbitses 
    singular: hobbit
    kind: Hobbit
    shortNames:
     - ht
```
After creating it, I start my python script. When I create the first resource, it tells me that it has been added. But, then a minute or so later, it tells me that it has been added again, despite there being no changes to it. In the following example, I have added a single resource. It has been repeated three times total. The last two times, the event has not differed from the first.

> python3 -u test.py 
> Starting stream
> Handling ADDED for bilbo-baggins:{'items': {'weapon': {'name': 'Sting', 'type': 'ShortSword'}}} version 455811
> Event was new!
> Handling ADDED for bilbo-baggins:{'items': {'weapon': {'name': 'Sting', 'type': 'ShortSword'}}} version 455811
> Handling ADDED for bilbo-baggins:{'items': {'weapon': {'name': 'Sting', 'type': 'ShortSword'}}} version 455811

The loop that executes this is here:

```python
running = True
resource_version = "" # Default to beginning of history
while running:
    old = None
    print("Starting stream")
    watcher = kubernetes.watch.Watch()
    stream = watcher.stream(crd_api.list_namespaced_custom_object,
                            "test.example",
                            "v1",
                            "", # Match all
                            "hobbitses",
                            resource_version = resource_version)
    for event in stream:
        obj = event["object"]
        op = event["type"]
        metadata = obj.get("metadata")
        name = metadata["name"]
        hobbit = obj.get("spec")

        resource_version = metadata["resourceVersion"]

        print("Handling %s for %s:%s version %s" % (op, name, hobbit, resource_version))

        if event != old:
            print("Event was new!")
        old = event
```

Digging into this a bit more, I found the following in Watch.Stream:

```python
        while True:
            resp = func(*args, **kwargs)
            try:
                for line in iter_resp_lines(resp):
                    yield self.unmarshal_event(line, return_type)
                    if self._stop:
                        break
            finally:
                kwargs['resource_version'] = self.resource_version
                resp.close()
                resp.release_conn()
```
[Link](https://github.com/karmab/samplecontroller/blob/fb0b45297d72a3d475c464692acf6da8a91942a0/controller.py#L52)

Thinking about this a bit, it seems to me like the issue is that the resource_version being passed to func is incorrect. 

The first time stream()'s for loop is called, the resource_version is the one passed in to stream(). That's fine. However, for subsequent iterations, the resource version is the value stored in the Watch object -- i.e. 0 if it's the default. This does not seem correct.

My understanding is that stream should be updating the resource version to the latest version handled in order to keep the streaming semantics.

FWIW, I was able to work around the issue by updating the Watch object's resource version prior to calling stream again.

E.g.
```python
...
        print("Handling %s for %s:%s version %s" % (op, name, hobbit, resource_version))

        watcher.resource_version = resource_version

        if event != old:
            print("Event was new!")
            old = event
```

While this works, it doesn't seem right for two reasons.

1. It is not documented
2. It breaks encapsulation; we really shouldn't need to understand the internals of Watch or the stream() function in order to use it.

I'd be fine with a documentation update, but I think the proper fix is to have the stream() function use the most recent resource version.

**Comment by tomplus** [comment]
Which version of the library do you use? There was a similar issue: https://github.com/kubernetes-client/python/issues/503 which is already fixed...

**Comment by klarose** [comment]
Somehow my google searches didn't find that. :)

Here's what I'm using:

> pip3 show kubernetes
> Name: kubernetes
> Version: 6.0.0
> Summary: Kubernetes python client
> Home-page: https://github.com/kubernetes-client/python
> Author: Kubernetes
> Author-email: UNKNOWN
> License: Apache License Version 2.0
> 

I took a look at my watch.py, and it does not have the lines added by that fix. So, clearly my version does not have it. 

It looks like that is the same issue, and my reading of the code is that it'd fix the problem. I'll see if I can get a version with the fix. Thanks!
