### ISSUE TITLE
stream assumes all data as UTF-8. That's not always the case.

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes-client/python-base#88]
```
resp = kubernetes.stream.stream(api.connect_get_namespaced_pod_exec, 'sleeping-bash', namespace='default', command=['bash', '-c', 'echo -n -e \\\\xD4'], stderr=True, stdin=False, stdout=True, tty=False)
```

```
site-packages\kubernetes\stream\ws_client.py in update(self, timeout)
    176            elif op_code == ABNF.OPCODE_BINARY or op_code == ABNF.OPCODE_TEXT:
    177                data = frame.data
    178                 if six.PY3:
--> 179                     data = data.decode("utf-8")
    180                 if len(data) > 1:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: unexpected end of data
```

**Comment by berlinsaint** [comment]
the same error here. I solve it by change to `data = data.decode("utf-8", "replace")`

but. when the file is encode by other charset, this code is not used.  any other solutions?

**Comment by roycaihw** [comment]
> when the file is encode by other charset, this code is not used. any other solutions?

from the [rfc](https://tools.ietf.org/html/rfc6455#section-5.6) we should decode uft8 for `OPCODE_TEXT` but leave `OPCODE_BINARY` as raw. this client should not assume encoding for arbitrary binary data

**Comment by leavest** [comment]
> the same error here. I solve it by change to `data = data.decode("utf-8", "replace")`
> 
> but. when the file is encode by other charset, this code is not used. any other solutions?

I get the same error when use vim command in web terminal.

**Comment by tbarrella** [comment]
https://github.com/kubernetes-client/python-base/commit/15474efbaf906bf557c4a38392a0b06c95ce7841 helped to fix the error above, but it seems like this issue should be re-opened with the intent of being able to stream bytes without trying to decode them
